### ISSUE TITLE
Mod could not be instanced / .cfg not generating

### ISSUE THREAD

**Issue by crash-mih** [FelixReuthlinger/AutoMapPins#1]
Hi, sorry to bother, but I don't understand how to get the config file to generate. I can edit the yaml just fine, but BepInEx doesn't seem to recognize it at all. Do you know how to fix it? 
Thank you!

**Comment by FelixReuthlinger** [comment]
Anything you do in YAML will not show in the BepInEx config manager, since it is a custom synced value, not a simple BepInEx config value. You can just edit in the file and game will show in the logs that it did load it.

**Comment by crash-mih** [comment]
It's not loading in though. It just says "Mod could not be instanced." and skips in the load queue.

**Comment by crash-mih** [comment]
After today's update, it's working fine! Not sure what happened.

**Comment by FelixReuthlinger** [comment]
ok, thx for letting me know ;)
