### ISSUE TITLE
Errors at launch and can't open console

### ISSUE THREAD

**Issue by MonolithTMA** [FelixReuthlinger/AutoMapPins#10]
`[Error  : Unity Log] MissingFieldException: Field 'FejdStartup.m_connectionFailedError' not found.
Stack trace:
(wrapper dynamic-method) FejdStartup.DMD<FejdStartup::ShowConnectError>(FejdStartup,ZNet/ConnectionStatus)
(wrapper dynamic-method) FejdStartup.DMD<FejdStartup::Start>(FejdStartup)

[Error  : Unity Log] MissingMethodException: void Terminal/ConsoleCommand..ctor(string,string,Terminal/ConsoleEvent,bool,bool,bool,bool,bool,Terminal/ConsoleOptionsFetcher,bool)
Stack trace:
(wrapper dynamic-method) Console.DMD<Console::Awake>(Console)
UnityEngine.Object:Instantiate(GameObject)
FejdStartup:DMD<FejdStartup::Awake>(FejdStartup)`

I just downloaded this mod this morning and received the above errors at launch and cannot open the console with F5. I removed this mod, and the errors did not reoccur.

**Comment by makouto** [comment]
Same here, the mod doesn't seem to work with the latest version of Valheim.

**Comment by makouto** [comment]
Thanks a lot for the update, it works perfectly again !

**Comment by MonolithTMA** [comment]
Yes, thanks so much for the update!

**Comment by FelixReuthlinger** [comment]
ok
