### ISSUE TITLE
Not an Issue - Switch House Icon to Round Pin?

### ISSUE THREAD

**Issue by MonolithTMA** [FelixReuthlinger/AutoMapPins#11]
I host a server, and my friends whom I play with don't use map-pinning mods. When I uninstall this mod to see what the pins look like without it, they show the house icon instead of the generic round pin icon. Is there a way to change that?

**Comment by FelixReuthlinger** [comment]
Nope, this cannot be simply changed, since this is due to the fact of Valheim and how game devs did setup pins. Creating a pin instance I first need to choose exact 1 of the existing pin types and can only later override the pin image. So, I used the first pin, which is the house.
