### ISSUE TITLE
[Suggestion] Allow for Default Pin Icons to be Used

### ISSUE THREAD

**Issue by SaltSouls** [FelixReuthlinger/AutoMapPins#13]
I mainly ask this so that we can turn on the boss pins without causing weird pin overlays, assuming the pins line up perfectly. That, or make it so that the boss pins placed by the compass get auto removed, and prevented from being auto placed at that point again, when the location has been discovered.

**Comment by FelixReuthlinger** [comment]
Overlapping pins cannot be avoided the way the game is implemented. If you find any just right click to remove one of them. There are no other ways to automate this unfortunately.
