### ISSUE TITLE
Adding discovery radius option

### ISSUE THREAD

**Issue by Kachelistic** [FelixReuthlinger/AutoMapPins#16]
I really like this mod cause it doesnt take much performance and has many configurable options. However this mod reveals almost a full range of minimap even outside the game's discovery range, so I couldnt keep this for it... Could you please add a discovery limit option and make it configurable?

+ I read closed #14 but I would rather exclude some objects and have this option, so please consider

**Comment by FelixReuthlinger** [comment]
Well, I did not add a configurable radius, but rather a feature that only the area that was explored on the map will set visible pins. Might even be better this way around, since some other mods also touch the range you discover things.
Check version 1.3.0
