### ISSUE TITLE
Ashland Internal Name Changes

### ISSUE THREAD

**Issue by Morpheus1101** [FelixReuthlinger/AutoMapPins#19]
For the most part this mod still functions as it should, however it would seem the Crypt an TrollCaves have had an internal name change and i cant seem to find what it was changed to in order to update the config.

**Comment by FelixReuthlinger** [comment]
thx for reporting, will need to check

**Comment by FelixReuthlinger** [comment]
as far as I can see there are "Crypt2", "Crypt3", "Crypt4", "TrollCave02" available in the game with the update. Since the mod logic does remove all numeric characters and turns everything lower case there should not be any effect.
