### ISSUE TITLE
Not an issue

### ISSUE THREAD

**Issue by DarthPhaethon** [FelixReuthlinger/AutoMapPins#2]
Wasn't sure how to otherwise get ahold of you.

Any plans for a GUI on this.?

**Comment by FelixReuthlinger** [comment]
What you mean with GUI? Pins are visible in game. GUI for configuration is not possible, since the game has was too many items to use default config manager for editing configs.

**Comment by BaldrAdmin** [comment]
@FelixReuthlinger - I checked some modding Discords, but didn't see your name over there. No bug/issue, but I wondered if it's possible to pin raft and ships? I tried adding an entry to the yaml, but it doesn't seem to pin them.

Here's what I tried (sorry, don't know how to format it correctly in this post):

ships:
  categoryActive: true
  pins:
    raft:
      categoryName: ships
      internalName: Raft
      name: Raft
      iconName: dot
      isPermanent: false
      isActive: true
      groupable: true
      groupingDistance: 32
    karve:
      categoryName: ships
      internalName: Karve
      name: Karve
      iconName: axe
      isPermanent: false
      isActive: true
      groupable: true
      groupingDistance: 32
    longship:
      categoryName: ships
      internalName: VikingShip
      name: Long Ship
      iconName: dot
      isPermanent: false
      isActive: true
      groupable: true
      groupingDistance: 32

**Comment by FelixReuthlinger** [comment]
well, ships are other types, but adding pins for them would also not work the same way, since they can move, where most other things that you can pin will not move. I think there are some other mods to pin ships ;)

**Comment by BaldrAdmin** [comment]
Ah! Okay. I'm really enjoying this new mod and thought I might be able to incorporate ships. Thanks for the quick reply!
