### ISSUE TITLE
Pins not showing up, Bepin throwing issue

### ISSUE THREAD

**Issue by Xanomenon** [FelixReuthlinger/AutoMapPins#21]
After the update we can't seem to get the mod to work. no pins are showing. We've tried various config combos to try to get it to trigger. Today I noticed a warning in Bepin.

[Warning:FixItFelix.AutoMapPins] no configuration found for config rockplains and category n_a - run console amp command and add config
[Warning:FixItFelix.AutoMapPins] no configuration found for config pickablestone and category n_a - run console amp command and add config
[Warning:FixItFelix.AutoMapPins] no configuration found for config seagal and category n_a - run console amp command and add config
[Warning:FixItFelix.AutoMapPins] no configuration found for config bushheath and category n_a - run console amp command and add config
[Warning:FixItFelix.AutoMapPins] no configuration found for config firtreeoldlog and category n_a - run console amp command and add config

**Comment by Xanomenon** [comment]
I did remove old config files just in case it was causeing it, and tried uninstalling and reinstalling, but still getting warnings. This one was from the black forest.

**[Warning:FixItFelix.AutoMapPins] no configuration found for config minerocktin and category n_a - run console amp command and add config
[Warning:FixItFelix.AutoMapPins] no configuration found for config blueberrybush and category n_a - run console amp command and add config
[Warning:FixItFelix.AutoMapPins] no configuration found for config pickablebranch and category n_a - run console amp command and add config
[Warning:FixItFelix.AutoMapPins] no configuration found for config pickablemushroomwitcheyetw and category n_a - run console amp command and add config
[Warning:FixItFelix.AutoMapPins] no configuration found for config treasurechestblackforest and category n_a - run console amp command and add config**

**Comment by FelixReuthlinger** [comment]
these warnings are just coming up if the mod does not find configs for the mentioned objects.
When I do test it with the latest Valheim version and the config that I do provide with the mod itself I can see pins. 
Maybe I forgot to add some pin configs or some object names from Valheim objects changed.

**Comment by FelixReuthlinger** [comment]
For example the branch is configured in the provided default config as:
```pickables_inactive:
  categoryActive: false
  pins:
    pickablebranch:
      categoryName: pickables_inactive
      internalName: pickablebranch
      name: Branch
      iconName: hand
      isPermanent: false
      isActive: false
      groupable: true
      groupingDistance: 15```

This default config will not show it, since there are too many of them.
If you removed this config entry, you may get this warning, if at the same time setting the config active to detect unmapped objects, of course.
