### ISSUE TITLE
Copper Pin still shows in new areas despite being disabled

### ISSUE THREAD

**Issue by Morpheus1101** [FelixReuthlinger/AutoMapPins#22]
Due to copper being quite easy an abundant to find, i have it turned off(as per below), however when discovering new area's the pIns for it are still loading.

pins:
    rockcopper:
      categoryName: ores
      internalName: rockcopper
      name: Copper
      iconName: mine
      isPermanent: false
      isActive: false

**Comment by FelixReuthlinger** [comment]
by still loading you mean they are displayed on the map?

**Comment by Morpheus1101** [comment]
Yes. I started off having them enabled an showing on the map, but later turned them off, while i didnt expect pre-existing markers on the map to disappear, i was surprised new areas uncovered would still have the Copper Map Pins placed irrespective of having them disabled.

**Comment by FelixReuthlinger** [comment]
I just uploaded the brand new 2.0 version of the mod, with this it brings many more features and should do a better job with config updates hopefully. Let me know any feedback :)
