### ISSUE TITLE
[Feature Request]: Remove All Pins Of Type From Map

### ISSUE THREAD

**Issue by Deadmano** [FelixReuthlinger/AutoMapPins#24]
Ability to wipe all pins of a given name from the map. In the event you made something permanent but now wish to remove it from your map altogether. Since once something is set as "permanent" and you turn it off to temporary, it will not update that pin to "fade away" when you get far away.

**Comment by FelixReuthlinger** [comment]
thanks for the request, I am currently looking into changing the way to load configs, so, it would also update pins, if you set them active or permanent during running game

**Comment by FelixReuthlinger** [comment]
Please have a look using the new 2.0 version of the mod, it does improve config loading, updating and brings many more nice features. I guess this will help to get the pins working better. Let me know any feedback :)
