### ISSUE TITLE
[Feature Request] Mark Enemies On Map In Real-Time

### ISSUE THREAD

**Issue by Deadmano** [FelixReuthlinger/AutoMapPins#26]
I use yet another map mod [UnderTheRadar](https://thunderstore.io/c/valheim/p/Kits_Bitz/UnderTheRadar/) to mark enemies, but it does not cover all enemy types and is not as extensive as your mod with the config to provide internal IDs etc. Any chance you can support live updates of mobs? Having them show on the map, preferably with icons relating to the enemy, be it an icon of theirs, or the material they drop as a worst-case?

**Comment by FelixReuthlinger** [comment]
Valheim's map implementation is not good for real time like things since markers and objects (creatures) are not connected and will not update as they move. The required workaround is quite performance intense and I will not add such a feature.

**Comment by Deadmano** [comment]
@FelixReuthlinger I know this was closed, but any chance you'd reconsider with your latest update?

[UnderTheRadar](https://thunderstore.io/c/valheim/p/Kits_Bitz/UnderTheRadar/) does it well, with no major performance impact despite over 50 pins. I'd rather use a singular mod that touches the same thing (map pins) and something that is more customisable. Regardless of the performance impact, if you give enough settings to tweak the user can mitigate as needed although as mentioned even with 50 pins updating the location of animals/enemies I didn't run into any performance issues.
