### ISSUE TITLE
Yaml file not found?

### ISSUE THREAD

**Issue by crolloS72** [FelixReuthlinger/AutoMapPins#28]
Hello. This is what I get when loading  V. 2.1.2

[Error  : Unity Log] ArgumentException: Directory does not exist
Parameter name: path
Stack trace:
System.IO.FileSystemWatcher..ctor (System.String path, System.String filter) (at <0176c56e11184037ab8bba48ad8e5607>:0)
System.IO.FileSystemWatcher..ctor (System.String path) (at <0176c56e11184037ab8bba48ad8e5607>:0)
(wrapper remoting-invoke-with-check) System.IO.FileSystemWatcher..ctor(string)
AutoMapPins.Data.YamlFileStorage.FindConfigFiles (System.String fileInfix) (at <d5904b32758e4e43934d7662f31dec61>:0)
AutoMapPins.Data.YamlFileStorage..ctor (System.String modGuid) (at <d5904b32758e4e43934d7662f31dec61>:0)
AutoMapPins.AutoMapPinsPlugin..cctor () (at <d5904b32758e4e43934d7662f31dec61>:0)
Rethrow as TypeInitializationException: The type initializer for 'AutoMapPins.AutoMapPinsPlugin' threw an exception.
UnityEngine.GameObject:AddComponent(Type)
BepInEx.Bootstrap.Chainloader:Start()
UnityEngine.GameObject:.cctor()
PlatformTools.Common.SingletonMonoBehaviour`1:get_Instance()
PlatformTools.PlatformManagerInitializer:OnRuntimeMethodLoad()

[Error  : Unity Log] ArgumentException: Directory does not exist
Parameter name: path
Stack trace:
System.IO.FileSystemWatcher..ctor (System.String path, System.String filter) (at <0176c56e11184037ab8bba48ad8e5607>:0)
System.IO.FileSystemWatcher..ctor (System.String path) (at <0176c56e11184037ab8bba48ad8e5607>:0)
(wrapper remoting-invoke-with-check) System.IO.FileSystemWatcher..ctor(string)
AutoMapPins.Data.YamlFileStorage.FindConfigFiles (System.String fileInfix) (at <d5904b32758e4e43934d7662f31dec61>:0)
AutoMapPins.Data.YamlFileStorage..ctor (System.String modGuid) (at <d5904b32758e4e43934d7662f31dec61>:0)
AutoMapPins.AutoMapPinsPlugin..cctor () (at <d5904b32758e4e43934d7662f31dec61>:0)
Rethrow as TypeInitializationException: The type initializer for 'AutoMapPins.AutoMapPinsPlugin' threw an exception.
UnityEngine.GameObject:AddComponent(Type)
BepInEx.Bootstrap.Chainloader:Start()
UnityEngine.GameObject:.cctor()
PlatformTools.Common.SingletonMonoBehaviour`1:get_Instance()
PlatformTools.PlatformManagerInitializer:OnRuntimeMethodLoad()

[LogOutput.log](https://github.com/user-attachments/files/15930072/LogOutput.log)

**Comment by FelixReuthlinger** [comment]
Thanks for reporting, this should be fixed already in future versions after 2.1.2
