### ISSUE TITLE
[V2.x] Default Vanilla Config Missing

### ISSUE THREAD

**Issue by Morpheus1101** [FelixReuthlinger/AutoMapPins#31]
Im not sure if its meant tobe created, but the previous vers to 2.0 had a Vanilla file which dosent seem to generate even with a fresh install of the mod...is this intentional?  I also do not see any issues i the LogOutput.log file.

**Comment by Morpheus1101** [comment]
Tested on a newly created profile and it worked quite fine...however on a pre-existing profile it was'nt generated.

**Comment by sfjuocekr** [comment]
It comes with the downloaded archive, not sure if it is generated.

**Comment by Morpheus1101** [comment]
Its changed locations...but it is..it places it in overrides dir
