### ISSUE TITLE
Mod Causes Client to Lock Up When trying to logout of an Active session

### ISSUE THREAD

**Issue by Morpheus1101** [FelixReuthlinger/AutoMapPins#33]
> [Error  : Unity Log] InvalidOperationException: Collection was modified; enumeration operation may not execute.
> Stack trace:
> System.Collections.Generic.Dictionary`2+Enumerator[TKey,TValue].MoveNext () (at <17d9ce77f27a4bd2afb5ba32c9bea976>:0)
> AutoMapPins.Model.Map.UpdatePins () (at <b1bbf93b00e84fe58e2eb7074d3e308f>:0)
> AutoMapPins.Data.Registry.InitializeRegistry (System.Collections.Generic.Dictionary`2[TKey,TValue] newConfiguredCategories) (at <b1bbf93b00e84fe58e2eb7074d3e308f>:0)
> AutoMapPins.AutoMapPinsPlugin.ReloadRegistry () (at <b1bbf93b00e84fe58e2eb7074d3e308f>:0)
> ServerSync.CustomSyncedValueBase.set_BoxedValue (System.Object value) (at <b1bbf93b00e84fe58e2eb7074d3e308f>:0)
> ServerSync.ConfigSync.resetConfigsFromServer () (at <b1bbf93b00e84fe58e2eb7074d3e308f>:0)
> ServerSync.ConfigSync+ResetConfigsOnShutdown.Postfix () (at <b1bbf93b00e84fe58e2eb7074d3e308f>:0)
> (wrapper dynamic-method) ZNet.DMD<ZNet::Shutdown>(ZNet,bool)
> Game.Shutdown (System.Boolean saveWorld) (at <67f3c386e04446c49523ecfd5b8921c2>:0)
> Game.ContinueLogout (System.Boolean save, System.Boolean shouldExit, System.Boolean changeToStartScene) (at <67f3c386e04446c49523ecfd5b8921c2>:0)
> (wrapper dynamic-method) Game.DMD<Game::Logout>(Game,bool,bool)
> Menu.Logout () (at <67f3c386e04446c49523ecfd5b8921c2>:0)
> Menu.OnLogoutYes () (at <67f3c386e04446c49523ecfd5b8921c2>:0)
> UnityEngine.Events.InvokableCall.Invoke () (at <ab14d35a27c043688812ae199c64b5aa>:0)
> UnityEngine.Events.UnityEvent.Invoke () (at <ab14d35a27c043688812ae199c64b5aa>:0)
> UnityEngine.UI.Button.Press () (at <4043a6cf2c744415844c8ec0cca11c21>:0)
> UnityEngine.UI.Button.OnPointerClick (UnityEngine.EventSystems.PointerEventData eventData) (at <4043a6cf2c744415844c8ec0cca11c21>:0)
> UnityEngine.EventSystems.ExecuteEvents.Execute (UnityEngine.EventSystems.IPointerClickHandler handler, UnityEngine.EventSystems.BaseEventData eventData) (at <4043a6cf2c744415844c8ec0cca11c21>:0)
> UnityEngine.EventSystems.ExecuteEvents.Execute[T] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.ExecuteEvents+EventFunction`1[T1] functor) (at <4043a6cf2c744415844c8ec0cca11c21>:0)
> UnityEngine.EventSystems.EventSystem:Update()

**Comment by FelixReuthlinger** [comment]
Thanks for the report, I will need to check this. Haven't encountered this issue myself, yet.

**Comment by FelixReuthlinger** [comment]
adding this to resolved list for 2.1.5
