### ISSUE TITLE
markers uploading to cartography table

### ISSUE THREAD

**Issue by braaaaains** [FelixReuthlinger/AutoMapPins#34]
The temporary markers created by this mod are uploading to the cartography table, so when playing on multiplayer others are receiving these markers and have to delete them one by one. Even without the mod, the markers are uploading to their maps, just with a ping icon instead of the custom icons. Is this happening for others?

**Comment by FelixReuthlinger** [comment]
Well, this is something I cannot change. Either all use the mod (should be set by server owner), or you don't use it at all. Or players using it don't use the table (or any other mod that transfers pins). This is due to the fact that pins displayed on the map need to be saved to the map and the table is just using it, not caring much about why a pin is on the map.

**Comment by braaaaains** [comment]
> Well, this is something I cannot change. Either all use the mod (should be set by server owner), or you don't use it at all. Or players using it don't use the table (or any other mod that transfers pins). This is due to the fact that pins displayed on the map need to be saved to the map and the table is just using it, not caring much about why a pin is on the map.

Right, but, even when I had one other person use the mod, the temporary map markers would get uploaded to the cartography table as permanent map markers and would have to each be manually deleted. Is there any way to make this just not interact with the cartography table maybe? Just for the sake of multiplayer

**Comment by FelixReuthlinger** [comment]
one thing I could give a try is to remove AMP pins before sharing the map data

**Comment by braaaaains** [comment]
Sorry where is that? How's that done? I also see that if I disable the mod to upload to the table with the intent to enable it again right afterwards, my own map is populated with yellow pings indicating every temporary map marker that was there before I quit the game with the mod enabled, so I have to remove each one manually. If there was a smoother way to enable/disable the mod off and on it would resolve the map table issue entirely... at least I think

**Comment by FelixReuthlinger** [comment]
I am on it, trying to write some code to do this

**Comment by braaaaains** [comment]
That's so nice of you, thank you so much!

**Comment by FelixReuthlinger** [comment]
So, the new 2.2.0 version should (hopefully, since I cannot test it myself) exclude the AMP pins from uploading to the table. please check if this helps

**Comment by braaaaains** [comment]
Hi! This seems to be fixed! I've tested it with multiple people! Thanks :)
