### ISSUE TITLE
Rune map icon doubles with ping after game start

### ISSUE THREAD

**Issue by frankiesek** [FelixReuthlinger/AutoMapPins#40]
Map gets pins like usual, but after I log out - and log back in - then all rune icons are replaced with ping icons - and rune icon is added after I come close

![obrazek](https://github.com/user-attachments/assets/a8de4640-c084-4211-af68-c200746ce602)

Single and multiplayer (dedicated server) both.

Rune config (yaml) - enabled and permanent.

runestones:
  categoryConfiguredObjects:
  - DrakeLorestone
  - Runestone_Ashlands
  - Runestone_BlackForest
  - Runestone_Boars
  - Runestone_Draugr
  - Runestone_Greydwarfs
  - Runestone_Meadows
  - Runestone_Mistlands
  - Runestone_Mountains
  - Runestone_Plains
  - Runestone_Swamps
  isActive: true
  isPermanent: true
  iconName: rune
  iconColorRGBA:
    red: 0
    green: 220
    blue: 255
    alpha: 255

**Comment by Morpheus1101** [comment]
I get a similar thing but with Copper since i have it disabled.

![image](https://github.com/user-attachments/assets/675cc6e0-0dc3-40ab-9b80-86eca5ffe20e)

**Comment by FelixReuthlinger** [comment]
> I get a similar thing but with Copper since i have it disabled.
> 
did you disable it while logged out? and this appears, when you login again?

**Comment by Morpheus1101** [comment]
Admittedly in my case, i did it while logged in and it worked, until i logged out an logged back in, then the above occurred for me.

**Comment by frankiesek** [comment]
I shut the game down, edited config (enabled) and then log in. No circles.

Explore, find some runes, log out, log back in - ping is there, rune is not. Unless I am close enough for the rune to appear (then there are two).

**Comment by FelixReuthlinger** [comment]
I really cannot tell, how this might be caused. I cannot reproduce it in singleplayer and I am not using servers...

**Comment by Morpheus1101** [comment]
I can reproduce my issue by having Copper icons pre-existing on the map & enabled in the yml file...Log off..disable copper pins..re-load game and the pre-existing icons have turned into the Ping Icon.

**Comment by frankiesek** [comment]
> I really cannot tell, how this might be caused. I cannot reproduce it in singleplayer and I am not using servers...

it does that for me in local singleplayer too.

**Comment by Dorennor** [comment]
Same bug, it seems when I set isPermanent option to "true", after login I got ping icons on my map.

**Comment by Dorennor** [comment]
I've added custom configs for berries and mushrooms

mushrooms:
  individualConfiguredObjects:
    Pickable_Mushroom:
      name: Mushroom (Red)
      isPermanent: true
      isActive: true
      groupable: true
    Pickable_Mushroom_yellow:
      name: Mushroom (Yellow)
      isPermanent: true
      isActive: true
      groupable: true
  isActive: true
  iconName: mushroom48
berries:
  individualConfiguredObjects:
    RaspberryBush:
      name: Raspberries
      isPermanent: true
      isActive: true
      groupable: true
    BlueberryBush:
      name: Blueberries
      isPermanent: true
      isActive: true
      groupable: true
    CloudberryBush:
      name: Cloudberries
      isPermanent: true
      isActive: true
      groupable: true
  isActive: true
  iconName: berry48
  
  also here changed config (in .txt file):
  
[Config.txt](https://github.com/user-attachments/files/17177642/Config.txt)

If need i can share my saves (local game) to provide further help. Love your mod so much and want to customize it so I will be happy if it will be possible to fix that bug)

**Comment by Dorennor** [comment]
It seems that there is here some conflict of options "isPermanent" and "groupable" but I think it needs further investigation.

**Comment by FelixReuthlinger** [comment]
this issue can happen if you combine some option in configuration that I would not recommend to combine, cannot do anything about it instead of reducing config options.
