### ISSUE TITLE
Console spam

### ISSUE THREAD

**Issue by zauberparacelsus** [FelixReuthlinger/AutoMapPins#7]
With this mod, I am seeing a ton of console spam related to modded objects that this mod isn't able to handle.  The amount of spam is enough to make it difficult or impossible to catch relevant error messages when I'm trying to debug other things.  This can also create possible performance issues, since it gets written to disk.

Would it be possible to add a config option to suppress the relevant console messages?

**Comment by Morpheus1101** [comment]
The console spam is very much killing FPS for myself with the pack we run often making the game unplayable evento the point of freezing the game so it needs to be force closed.

**Comment by FelixReuthlinger** [comment]
Well, you can simply avoid the spam by also configuring the prefabs that are not configured. I usually do this by even god-mode flying through the world. It then writes a lot of logs, yes, but this never killed my laptop ;)

But anyways will add some new config options, so, you can turn it off, even if not everything is configured.

**Comment by FelixReuthlinger** [comment]
1.2.0 released
