### ISSUE TITLE
Not able to get pins for Mod ores working

### ISSUE THREAD

**Issue by Morpheus1101** [FelixReuthlinger/AutoMapPins#8]
Below is what i've got added to the FixItFelix.AutoMapPins.categories.vanilla.yaml file, but none of it is working and im not sure what im missing to why it isnt(spacings between each one is just for readability on github)

   flametal:
      categoryName: ores
      internalName: MineRock_Meteorite
      name: Flametal
      iconName: mine
      isPermanent: true
      isActive: true

    valhallium:
      categoryName: ores
      internalName: MineRock_FroOre_DoD
      name: Valhallium
      iconName: mine
      isPermanent: true
      isActive: true

    glacialcrystal:
      categoryName: ores
      internalName: MineRock_GlacierFragment_TW
      name: GlacialCrystal
      iconName: mine
      isPermanent: true
      isActive: true  
    
    tyranium:
      categoryName: ores
      internalName: MineRock_Tyranium_TW
      name: Tyranium
      iconName: mine
      isPermanent: true
      isActive: true      

    volcanic:
      categoryName: ores
      internalName: MineRock_VolcanicFragment_TW
      name: VolcanicCrystal
      iconName: mine
      isPermanent: true
      isActive: true      
  
    primordialice:
      categoryName: ores
      internalName: ice_rock1
      name: PrimordialIce
      iconName: mine
      isPermanent: true
      isActive: true

    primordialice1:
      categoryName: ores
      internalName: ice_rock1_frac
      name: PrimordialIce
      iconName: mine
      isPermanent: true
      isActive: true

**Comment by Morpheus1101** [comment]
The issue is what the actual prefab name in game is, is not what is expected here, its expecetd all lower case, no underscores or anything, so the documentation on the main page of the github to me seems incorrect.

**Comment by FelixReuthlinger** [comment]
https://github.com/FelixReuthlinger/AutoMapPins#yaml-internal-name-parsing should help to understand how prefab names get parsed

**Comment by Morpheus1101** [comment]
Guess i need to get new glasses as i totally missed that section, explains quite a bit.
