### ISSUE TITLE
mod showing unexist character and cant play solo

### ISSUE THREAD

**Issue by meigrafd** [FelixReuthlinger/AutoMapPins#9]
- When i load this mod my game shows an non exist player character " Ragnar " in mainmenu. after scrolling to my exists, Ragnar is gone.
- But the other problem is also that i cant start a singeplayer game nor a local multiplayergame. 
- Also the remote serverlist of my own is each game restart gone.
- Server_devcommands stops working.
- I cant open the console.
- And BepInEx Infos arent displayd in mainmenu.

After disabling AutoMapPins everything works fine. 

My Modlist:
```
BepInExPack_Valheim
Official_BepInEx_ConfigurationManager by Azumatt
HookGenPatcher by ValheimModding
Jotunn by ValheimModding
Server_devcommands by JereKuusela
UseEquipmentInWater by LVH-IT
PlanBuild by MathiasDecrock
RenegadeVikings by blacks7ar
ValheimRAFTUpdated by Mega_Team
Armory by Therzie
Warfare by Therzie
WarfareFireAndIce by Therzie
ItemDrawers by makail
Recycle_N_Reclaim by Azumatt
AdjustTamingSpeed by n9tro
More_Gates by Thordomr
PlantEverything by Advize
TeleportEverything by OdinPlus
QuickTeleport by OdinPlus
AutoMapPins by FixItFelix
```

**Comment by LadyWolfheart** [comment]
Exact same issue, though different modlist. Problem is definitely this mod.

**Comment by CapTV8** [comment]
Yep, same here.  I know IG released two patches close to each other so it was probably fixed for the first patch but then the 2nd patch messed up a lot of mods again.  Thanks, Felix! <3

EDIT:  works now with 1.2.2 update.  Thanks, Felix!

Any way to track silvervein_frac ?  I added to YAML file but it's not working.

**Comment by FelixReuthlinger** [comment]
yep, if IG updates valheim, some things break and need to get updated. I was on vacation now 2 weeks, but I think this was already fixed before, right?
